services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viresh-portfolio
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.local`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=8080"

  # Optional: Add a reverse proxy for production
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - production
    restart: unless-stopped

volumes:
  nginx_cache:
    driver: local

networks:
  default:
    name: portfolio-network
