version: '3.8'

services:
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viresh-portfolio-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development server (alternative to nginx)
  dev-server:
    image: nginx:alpine
    container_name: portfolio-dev-server
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    profiles:
      - dev-server
    restart: unless-stopped

networks:
  default:
    name: portfolio-dev-network
